<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Speciality;
use Illuminate\Database\Seeder;

class SpecialitySeeder extends Seeder
{
    public function run(): void
    {
        Speciality::create(['code' => '502', 'new_code' => '100', 'name' => 'EDUCACION, MENCION TECNICA INDUSTRIAL MECANICA', 'title' => 'LICENCIADO EN EDUCACION INDUSTRIAL, MENCION MECANICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '687', 'new_code' => '101', 'name' => 'TRABAJO SOCIAL (TECNICO)', 'title' => 'TECNICO EN TRABAJO SOCIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '801', 'new_code' => '102', 'name' => 'INGENIERIA DE GAS', 'title' => 'ACTUALIZACION PROFESIONAL EN INGENIERIA DE GAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '802', 'new_code' => '103', 'name' => 'ANESTESIOLOGIA', 'title' => 'ESPECIALISTA EN ANESTESIOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '803', 'new_code' => '104', 'name' => 'CARDIOLOGIA', 'title' => 'ESPECIALISTA EN CARDIOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '804', 'new_code' => '105', 'name' => 'CIENCIA DE LOS ALIMENTOS', 'title' => 'ESPECIALISTA EN CIENCIA DE LOS ALIMENTOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '805', 'new_code' => '106', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCION ADMINISTRACION DE LA PRODUCCION', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '806', 'new_code' => '107', 'name' => 'ESP. CS. ADM. MENC. FINANZAS', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCION FINANZAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '807', 'new_code' => '108', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCION GERENCIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '808', 'new_code' => '109', 'name' => 'ESP. CS. ADM. MENC. GERENCIA', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCION GERENCIA GENERAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '809', 'new_code' => '110', 'name' => 'CIRUGIA GENERAL', 'title' => 'ESPECIALISTA EN CIRUGIA GENERAL', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '810', 'new_code' => '111', 'name' => 'GERENCIA HOTELERA', 'title' => 'ESPECIALISTA EN GERENCIA HOTELERA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '811', 'new_code' => '112', 'name' => 'GINECOLOGIA Y OBSTETRICIA', 'title' => 'ESPECIALISTA EN GINECOLOGIA Y OBTETRICIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '812', 'new_code' => '113', 'name' => 'INFORMATICA GERENCIAL', 'title' => 'ESPECIALISTA EN INFORMATICA GERENCIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '813', 'new_code' => '114', 'name' => 'MEDICINA FAMILIAR', 'title' => 'ESPECIALISTA EN MEDICINA FAMILIAR', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '814', 'new_code' => '115', 'name' => 'MEDICINA INTERNA', 'title' => 'ESPECIALISTA EN MEDICINA INTERNA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '815', 'new_code' => '116', 'name' => 'MERCADEO TURISTICO', 'title' => 'ESPECIALISTA EN MERCADEO TURISTICO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '816', 'new_code' => '117', 'name' => 'PEDIATRIA Y PUERICULTURA', 'title' => 'ESPECIALISTA EN PUERICULTURA Y PEDIATRIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '817', 'new_code' => '118', 'name' => 'PLANIFICACION TURISTICA', 'title' => 'ESPECIALISTA EN PLANIFICACION TURISTICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '818', 'new_code' => '119', 'name' => 'PSIQUIATRIA', 'title' => 'ESPECIALISTA EN PSIQUIATRIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '819', 'new_code' => '120', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCION MERCADOTECNIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '820', 'new_code' => '121', 'name' => 'TRAUMATOLOGIA Y ORTOPEDIA', 'title' => 'ESPECIALISTA EN TRAUMATOLOGIA Y ORTOPEDIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '821', 'new_code' => '122', 'name' => 'TURISMO', 'title' => 'ESPECIALISTA EN TURISMO MENCION GERENCIA HOTELERA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '822', 'new_code' => '123', 'name' => 'TURISMO', 'title' => 'ESPECIALISTA EN TURISMO MENCION PLANIFICACION TURISTICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '823', 'new_code' => '124', 'name' => 'AGRICULTURA TROPICAL', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MENCION BOTANICA AGRICOLA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '824', 'new_code' => '125', 'name' => 'AGRICULTURA TROPICAL', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MENCION FISIOLOGIA VEGETAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '825', 'new_code' => '126', 'name' => 'BIOLOGIA APLICADA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA MENCION BOTANICA APLICADA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '826', 'new_code' => '127', 'name' => 'BIOLOGIA APLICADA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA MENCION ECOFISIOLOGIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '827', 'new_code' => '128', 'name' => 'BIOLOGIA APLICADA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA MENCION MICROBIOLOGIA APLICADA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '828', 'new_code' => '129', 'name' => 'CIENCIA DE LOS ALIMENTOS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIA DE LOS ALIMENTOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '829', 'new_code' => '130', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION ADMINISTRACION AGRICOLA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '830', 'new_code' => '131', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION ADMINISTRACION DE LA PRODUCCION', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '831', 'new_code' => '132', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION FINANZAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '832', 'new_code' => '133', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION GERENCIA GENERAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '833', 'new_code' => '134', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION MERCADOTECNIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '834', 'new_code' => '135', 'name' => 'CIENCIAS MARINAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS MARINAS MENCION BIOLOGIA MARINA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '835', 'new_code' => '136', 'name' => 'CIENCIAS MARINAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS MARINAS MENCION BIOLOGIA PESQUERA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '836', 'new_code' => '137', 'name' => 'CIENCIAS MARINAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS MARINAS MENCION OCEANOGRAFIA QUIMICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '837', 'new_code' => '138', 'name' => 'EDUCACION', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACION MENCION ENSEÑANZA DE LA FISICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '838', 'new_code' => '139', 'name' => 'EDUCACION', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACION MENCION ENSEÑANZA DE LAS MATEMATICAS BÁSICAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '839', 'new_code' => '140', 'name' => 'EDUCACION', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACION MENCION ENSEÑANZA DEL CASTELLANO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '840', 'new_code' => '141', 'name' => 'EDUCACION', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACION MENCION ENSEÑANZA DEL INGLES COMO IDIOMA EXTRANJERO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '841', 'new_code' => '142', 'name' => 'FISICA', 'title' => 'MAGISTER SCIENTIARUM EN FISICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '842', 'new_code' => '143', 'name' => 'INFORMATICA GERENCIAL', 'title' => 'MAGISTER SCIENTIARUM EN INFORMATICA GERENCIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '843', 'new_code' => '144', 'name' => 'INGENIERIA DE LOS ALIMENTOS', 'title' => 'MAGISTER SCIENTIARUM EN INGENIERIA DE LOS ALIMENTOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '844', 'new_code' => '145', 'name' => 'MAGISTER SCIENTIARUM EN INGENIERIA QUIMICA', 'title' => 'MAGISTER SCIENTIARUM EN INGENIERIA QUIMICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '845', 'new_code' => '146', 'name' => 'MAGISTER SCIENTIARUM EN MATEMATICA', 'title' => 'MAGISTER SCIENTIARUM EN MATEMATICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '846', 'new_code' => '147', 'name' => 'PLANIFICACION DEL DESARROLLO REGIONAL', 'title' => 'MAGISTER SCIENTIARUM EN PLANIFICACION DEL DESARROLLO REGIONAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '847', 'new_code' => '148', 'name' => 'SALUD PUBLICA', 'title' => 'MAGISTER SCIENTIARUM EN SALUD PUBLICA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '848', 'new_code' => '149', 'name' => 'SALUD PUBLICA', 'title' => 'MAGISTER SCIENTIARUM EN SALUD PUBLICA MENCION ADMINISTRACION SANITARIA INTEGRAL', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '849', 'new_code' => '150', 'name' => 'SALUD PUBLICA', 'title' => 'MAGISTER SCIENTIARUM EN SALUD PUBLICA MENCION EPIDEMIOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '850', 'new_code' => '151', 'name' => 'MAGISTER SCIENTIARUM EN TURISMO', 'title' => 'MAGISTER SCIENTIARUM EN TURISMO MENCION GERENCIA HOTELERA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '851', 'new_code' => '152', 'name' => 'MAGISTER SCIENTIARUM EN TURISMO', 'title' => 'MAGISTER SCIENTIARUM EN TURISMO MENCION MERCADEO TURISTICO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '852', 'new_code' => '153', 'name' => 'MAGISTER SCIENTIARUM EN TURISMO', 'title' => 'MAGISTER SCIENTIARUM EN TURISMO MENCION PLANIFICACION TURISTICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '853', 'new_code' => '154', 'name' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN DE EMPRESAS', 'title' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN DE EMPRESAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '854', 'new_code' => '155', 'name' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN DE EMPRESAS MENCIÓN FINANZAS', 'title' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN DE EMPRESAS MENCIÓN FINANZAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '855', 'new_code' => '156', 'name' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN EDUCATIVA', 'title' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN EDUCATIVA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '856', 'new_code' => '157', 'name' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN EMPRESAS TURÍSTICAS MENCIÓN HOTELERÍA', 'title' => 'MAGISTER SCIENTIARUM EN ADMINISTRACIÓN EMPRESAS TURÍSTICAS MENCIÓN HOTELERÍA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '857', 'new_code' => '158', 'name' => 'DERMATOLOGIA', 'title' => 'ESPECIALISTA EN DERMATOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '858', 'new_code' => '159', 'name' => 'CIENCIAS MARINAS', 'title' => 'DOCTOR EN CIENCIAS MARINAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '859', 'new_code' => '160', 'name' => 'ESPECIALISTA EN MERCADEO TURISTICO', 'title' => 'ESPECIALISTA EN MERCADEO TURISTICO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '860', 'new_code' => '161', 'name' => 'INGENIERIA DE GAS', 'title' => 'ESPECIALISTA EN INGENIERIA DE GAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '861', 'new_code' => '162', 'name' => 'BIOLOGIA APLICADA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA MENCION ECOLOGIA TOXICOLOGIA AMBIENTAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '862', 'new_code' => '163', 'name' => 'INGENIERIA MECANICA', 'title' => 'MAGISTER SCIENTIARUM EN INGENIERIA MECANICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '863', 'new_code' => '164', 'name' => 'POZOS PETROLEROS', 'title' => 'ESPECIALISTA EN POZOS PETROLEROS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '865', 'new_code' => '165', 'name' => 'AGRONOMO', 'title' => 'ESPECIALISTA AGRONOMO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '866', 'new_code' => '166', 'name' => 'TRABAJO SOCIAL', 'title' => 'ESPECIALISTA EN TRABAJO SOCIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '867', 'new_code' => '167', 'name' => 'MICROSCOPIA ELECTRONICA', 'title' => 'MAGISTER SCIENTIARUM EN MICROSCOPIA ELECTRONICA MENCION CIENCIAS BIOMEDICAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '868', 'new_code' => '168', 'name' => 'CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS MENCION ADMINISTRACION DE EMPRESAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '869', 'new_code' => '169', 'name' => 'MAESTRIA EN CIENCIAS', 'title' => 'MAGISTER SCIENTIARUM EN GERIATRIA Y GERONTOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '870', 'new_code' => '170', 'name' => 'MAESTRIA EN CIENCIAS', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL, MENCION PLANTAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '871', 'new_code' => '171', 'name' => 'MAESTRIA EN CIENCIAS', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL, MENCION PRODUCCION VEGETAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '872', 'new_code' => '172', 'name' => 'MAESTRIA EN CIENCIAS ADMINISTRATIVAS', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS ADMINISTRATIVAS, MENCION GERENCIA GENERAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '873', 'new_code' => '173', 'name' => 'ESPECIALISTA EN RECURSOS NATURALES', 'title' => 'ESPECIALISTA EN RECURSOS NATURALES', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '874', 'new_code' => '174', 'name' => 'MAGISTER', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACION MENCION ENSEÑANZA DE LA QUIMICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '875', 'new_code' => '175', 'name' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MEMENCION EDAFOLOGIA', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MENCION EDAFOLOGIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '876', 'new_code' => '176', 'name' => 'MAGISTER SCIENTIARUM EN CIENCIAS MARINAS MENCIÓN OCEANOGRAFÍA FÍSICA', 'title' => 'MAGISTER SCIENTIARUM EN CIENCIAS MARINAS MENCIÓN OCEANOGRAFÍA FÍSICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '877', 'new_code' => '177', 'name' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCIÓN ADMINISTRACIÓN AGRÍCOLA', 'title' => 'ESPECIALISTA EN CIENCIAS ADMINISTRATIVAS MENCIÓN ADMINISTRACIÓN AGRÍCOLA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '890', 'new_code' => '178', 'name' => 'ESPECIALISTA EN GERIATRIA Y GERONTOLOGIA', 'title' => 'ESPECIALISTA EN GEREATRIA Y GERONTOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '891', 'new_code' => '179', 'name' => 'ESPECIALISTA EN RECURSOS NATURALES MENCION RECURSOS HIDRAULICOS', 'title' => 'ESPECIALISTA EN RECURSOS NATURALES MENCION RECURSOS HIDRAULICOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '892', 'new_code' => '180', 'name' => 'ESPECIALISTA EN RECURSOS NATURALES MENCION RECURSOS MINERALES', 'title' => 'ESPECIALISTA EN RECURSOS NATURALES MENCION RECURSOS MINERALES', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '893', 'new_code' => '181', 'name' => 'ESPECIALISTA', 'title' => 'ESPECIALISTA EN INGENIERIA DE MANTENIMIENTO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '894', 'new_code' => '182', 'name' => 'EDUCACION', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACIÓN MENCIÓN PLANIFICACIÓN EDUCATIVA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '895', 'new_code' => '183', 'name' => 'MAGISTER SCIENTIARUM EN TURISMO', 'title' => 'MAGISTER SCIENTIARUM EN TURISMO', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '896', 'new_code' => '184', 'name' => 'ESP. EN ING. ELECT. MEN. AUTOMATIZACION E INFORMATICA INDUSTRIAL', 'title' => 'ESPECIALISTA EN AUTOMATIZACION E INFORMATICA INDUSTRIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '897', 'new_code' => '185', 'name' => 'ESPECIALISTA EN', 'title' => 'ESPECIALISTA EN AUTOMATIZACION E INFORMATICA INDUSTRIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '898', 'new_code' => '186', 'name' => 'ESPECIALISTA EN NEFROLOGIA', 'title' => 'ESPECIALISTA EN NEFROLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '899', 'new_code' => '187', 'name' => 'SALUD PUBLICA', 'title' => 'MAGÍSTER SCIENTIARUM EN SALUD PÚBLICA MENCIÓN ADMINISTRACIÓN DE LA ATENCIÓN MÉDICA HOSPITALARIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '900', 'new_code' => '188', 'name' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '901', 'new_code' => '189', 'name' => 'ESPECIALISTA EN MEDICINA DE EMERGENCIA Y DESASTRE', 'title' => 'ESPECIALISTA EN MEDICINA DE EMERGENCIA Y DESASTRE', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '902', 'new_code' => '190', 'name' => 'EDUCACIÓN', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACIÓN MENCIÓN ADMINISTRACIÓN EDUCATIVA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '903', 'new_code' => '191', 'name' => 'EDUC. MENCION DOCENCIA EN EDUC. SUP.', 'title' => 'MAGISTER SCIENTIARUM EN EDUCACIÓN MENCIÓN DOCENCIA EN EDUCACIÓN SUPERIOR', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '904', 'new_code' => '192', 'name' => 'DOCTORADO EN EDUCACION', 'title' => 'DOCTOR EN EDUCACION', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '905', 'new_code' => '193', 'name' => 'ECOTOXICOLOGIA', 'title' => 'MAGISTER SCIENTIARUM EN BIOLOGIA APLICADA MENCION ECOTOXICOLOGIA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '906', 'new_code' => '194', 'name' => 'ING. ELECT. MENCION AUTOMATIZACION E INF. IND.', 'title' => 'MAGÍSTER SC. EN INGENIERIA ELECTRICA MENCION AUTOMATIZACION E INFORMATICA INDUSTRIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '907', 'new_code' => '195', 'name' => 'CIENCIAS ADMINISTRATIVAS MENCIÓN RECURSOS HUMANOS', 'title' => 'MAGISTER SCIENTIARUN EN CIENCIAS ADMINISTRATIVAS MENCION GERENCIA DE RECURSOS HUMANOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '908', 'new_code' => '196', 'name' => 'TECNICO SUPERIOR ESPECILISTA', 'title' => 'TECNICO SUPERIOR ESPECIALISTA EN CIENCIAS DE LOS ALIMENTOS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '909', 'new_code' => '197', 'name' => 'ESP. INGENIERÍA DE YACIMIENTO DE GAS', 'title' => 'ESPECIALISTA EN INGENIERÍA DE YACIMIENTO DE GAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '910', 'new_code' => '198', 'name' => 'ESP. EN PRODUCTIVIDAD DE POZOS', 'title' => 'ESPECIALISTA EN PRODUCTIVIDAD DE POZOS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '911', 'new_code' => '199', 'name' => 'MAGISTER SCIENTIARUM EN QUÍMICA', 'title' => 'MAGISTER SCIENTIARUM EN QUÍMICA', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '912', 'new_code' => '200', 'name' => 'TECNICO SUPERIOR ESPECIALISTA EN MERCADEO TURISTICO', 'title' => 'TECNICO SUPERIOR ESPECIALISTA EN MERCADEO TURISTICO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '913', 'new_code' => '201', 'name' => 'Doctor Honoris causa', 'title' => 'Doctor Honoris Causa en Ciencias Médicas', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '914', 'new_code' => '202', 'name' => 'MAGISTER EN RECURSOS NATURALES MENCIÓN RECURSOS MINERALES', 'title' => 'MAGISTER SCIENTIARUM EN RECURSOS NATURALES MENCIÓN RECURSOS MINERALES', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '915', 'new_code' => '203', 'name' => 'ESPECIALISTA EN INGENIERÍA ELÉCTRICA MENCIÓN AUTOMATIZACIÓN E INFORMÁTICA INDUSTRIAL', 'title' => 'ESPECIALISTA EN INGENIERÍA ELÉCTRICA MENCIÓN AUTOMATIZACIÓN E INFORMÁTICA INDUSTRIAL', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '916', 'new_code' => '204', 'name' => 'ESPECIALISTA EN NEUROCIRUGÍA', 'title' => 'ESPECIALISTA EN NEUROCIRUGÍA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '917', 'new_code' => '205', 'name' => 'ESPECIALISTA EN OFTALMOLOGIA', 'title' => 'ESPECIALISTA EN OFTALMOLOGIA', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '918', 'new_code' => '206', 'name' => 'CIENCIA DE LOS MATERIALES', 'title' => 'DOCTOR EN CIENCIA DE LOS MATERIALES', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '919', 'new_code' => '207', 'name' => 'ESPECIALISTA EN CIRUGÍA DE LA MANO Y RECONSTRUCTIVA DEL MIEMBRO SUPERIOR', 'title' => 'ESPECIALISTA EN CIRUGÍA DE LA MANO Y RECONSTRUCTIVA DEL MIEMBRO SUPERIOR', 'type' => '2', 'health_type' => '2']);
        Speciality::create(['code' => '920', 'new_code' => '208', 'name' => 'DOCTOR EN CIENCIA DE LOS MATERIALES', 'title' => 'DOCTOR EN CIENCIA DE LOS MATERIALES', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '921', 'new_code' => '209', 'name' => 'DOCTOR EN MATEMATICAS', 'title' => 'DOCTOR EN MATEMATICAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '922', 'new_code' => '210', 'name' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MENCION MEJORAMIENTO DE PLANTAS', 'title' => 'MAGISTER SCIENTIARUM EN AGRICULTURA TROPICAL MENCION MEJORAMIENTO DE PLANTAS', 'type' => '2', 'health_type' => '1']);
        Speciality::create(['code' => '1000', 'new_code' => '211', 'name' => 'LICENCIATURA EN QUIMICA', 'title' => 'LICENCIADO EN QUIMICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '1005', 'new_code' => '212', 'name' => 'FISICA', 'title' => 'LICENCIADO EN FISICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '1010', 'new_code' => '213', 'name' => 'LICENCIATURA EN MATEMATICA', 'title' => 'LICENCIADO EN MATEMATICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '1015', 'new_code' => '214', 'name' => 'BIOLOGIA', 'title' => 'LICENCIADO EN BIOLOGIA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2035', 'new_code' => '215', 'name' => 'INGENIERIA DE MINAS', 'title' => 'INGENIERO DE MINAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2040', 'new_code' => '216', 'name' => 'INGENIERIA GEOLOGICA', 'title' => 'INGENIERO GEOLOGO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2045', 'new_code' => '217', 'name' => 'GEOLOGIA', 'title' => 'GEOLOGO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2060', 'new_code' => '218', 'name' => 'INGENIERIA DE PETROLEO', 'title' => 'INGENIERO DE PETROLEO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2065', 'new_code' => '219', 'name' => 'INGENIERIA EN COMPUTACION', 'title' => 'INGENIERO EN COMPUTACION', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2074', 'new_code' => '220', 'name' => 'LICENCIATURA EN INFORMATICA', 'title' => 'LICENCIADO EN INFORMATICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2075', 'new_code' => '221', 'name' => 'INGENIERIA DE SISTEMAS', 'title' => 'INGENIERO DE SISTEMAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2076', 'new_code' => '222', 'name' => 'INGENIERIA DE SISTEMAS', 'title' => 'INGENIERO DE SISTEMAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2085', 'new_code' => '223', 'name' => 'INGENIERIA ELECTRICA', 'title' => 'INGENIERO ELECTRICISTA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2105', 'new_code' => '224', 'name' => 'INGENIERIA MECANICA', 'title' => 'INGENIERO MECANICO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2110', 'new_code' => '225', 'name' => 'INGENIERIA QUIMICA', 'title' => 'INGENIERO QUIMICO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2115', 'new_code' => '226', 'name' => 'INGENIERIA INDUSTRIAL', 'title' => 'INGENIERO INDUSTRIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2120', 'new_code' => '227', 'name' => 'INGENIERIA CIVIL', 'title' => 'INGENIERO CIVIL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2126', 'new_code' => '228', 'name' => 'ARQUITECTURA', 'title' => 'ARQUITECTO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2555', 'new_code' => '229', 'name' => 'TECNOLOGIA EN ELECTRONICA', 'title' => 'TECNOLOGO EN ELECTRONICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2590', 'new_code' => '230', 'name' => 'TECNOLOGIA DE FABRICACION MECANICA', 'title' => 'TECNOLOGO EN FABRICACION MECANICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2591', 'new_code' => '231', 'name' => 'TECNOLOGIA DE FABRICACION MECANICA', 'title' => 'TECNOLOGO EN FABRICACION MECANICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2600', 'new_code' => '232', 'name' => 'TECNOLOGIA DE ALIMENTOS', 'title' => 'TÉCNICO SUPERIOR EN TECNOLOGIA DELOS ALIMENTOS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2625', 'new_code' => '233', 'name' => 'TECNOLOGIA EN SISTEMAS INDUSTRIALES', 'title' => 'TECNOLOGO EN SISTEMAS INDUSTRIALES', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '2665', 'new_code' => '234', 'name' => 'TECNOLOGIA EN CONSTRUCCION CIVIL', 'title' => 'TECNOLOGO EN CONSTRUCCION CIVIL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3135', 'new_code' => '235', 'name' => 'INGENIERIA AGRONOMICA', 'title' => 'INGENIERO AGRONOMO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3192', 'new_code' => '236', 'name' => 'BIOLOGIA MARINA', 'title' => 'LICENCIADO EN BIOLOGIA MARINA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3194', 'new_code' => '237', 'name' => 'BIOLOGIA PESQUERA', 'title' => 'LICENCIADO EN BIOLOGIA PESQUERA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3195', 'new_code' => '238', 'name' => 'LIC. ACUACULTURA', 'title' => 'LICENCIADO EN ACUACULTURA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3200', 'new_code' => '239', 'name' => 'TECNOLOGIA DE ALIMENTOS', 'title' => 'LICENCIADO EN TECNOLOGIA DE ALIMENTOS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3480', 'new_code' => '240', 'name' => 'INGENIERIA DE PRODUCCION ANIMAL', 'title' => 'INGENIERO DE PRODUCCION ANIMAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '3856', 'new_code' => '241', 'name' => 'ZOOTECNISTA', 'title' => 'ZOOTECNISTA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '4205', 'new_code' => '242', 'name' => 'MEDICINA', 'title' => 'MEDICO CIRUJANO', 'type' => '1', 'health_type' => '2']);
        Speciality::create(['code' => '4210', 'new_code' => '243', 'name' => 'ENFERMERIA', 'title' => 'LICENCIADO EN ENFERMERIA', 'type' => '1', 'health_type' => '2']);
        Speciality::create(['code' => '4215', 'new_code' => '244', 'name' => 'LICENCIATURA EN BIOANALISIS', 'title' => 'LICENCIADO EN BIOANALISIS', 'type' => '1', 'health_type' => '2']);
        Speciality::create(['code' => '4756', 'new_code' => '245', 'name' => 'TECNICO SUPERIOR EN ENFERMERIA', 'title' => 'TECNICO SUPERIOR EN ENFERMERIA', 'type' => '1', 'health_type' => '2']);
        Speciality::create(['code' => '5000', 'new_code' => '246', 'name' => 'LICENCIATURA EN ADMINISTRACION', 'title' => 'LICENCIADO EN ADMINISTRACION', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5245', 'new_code' => '247', 'name' => 'EDUCACION INTEGRAL', 'title' => 'LICENCIADO EN EDUCACION INTEGRAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5257', 'new_code' => '248', 'name' => 'EDUCACION MENCION BIOLOGIA', 'title' => 'LICENCIADO EN EDUCACION, MENCION BIOLOGIA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5260', 'new_code' => '249', 'name' => 'EDUCACION, MENCION MATEMATICA', 'title' => 'LICENCIADO EN EDUCACION, MENCION MATEMATICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5265', 'new_code' => '250', 'name' => 'EDUCACION, MENCION FISICA', 'title' => 'LICENCIADO EN EDUCACION, MENCION FISICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5267', 'new_code' => '251', 'name' => 'LICENCIATURA EN EDUCACION MENCION QUIMICA', 'title' => 'LICENCIADO EN EDUCACION, MENCION QUIMICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5275', 'new_code' => '252', 'name' => 'EDUCACIÓN TÉCNICA INDUSTRIAL', 'title' => 'LICENCIADO EN EDUCACION MENCION TÉCNICA INDUSTRIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5295', 'new_code' => '253', 'name' => 'EDUCACION, MENCION TECNICA MERCANTIL', 'title' => 'LICENCIADO EN EDUCACION, MENCION TECNICA MERCANTIL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5310', 'new_code' => '254', 'name' => 'LICENCIATURA EN EDUCACION MENCION CASTELLANO Y LITERATURA', 'title' => 'LICENCIADO EN EDUCACION, MENCION CASTELLANO Y LITERATURA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5315', 'new_code' => '255', 'name' => 'EDUCACION, MENCION INGLES', 'title' => 'LICENCIADO EN EDUCACION, MENCION INGLES', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6335', 'new_code' => '256', 'name' => 'LICENCIATURA EN ESTADISTICA', 'title' => 'LICENCIADO EN ESTADISTICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6350', 'new_code' => '257', 'name' => 'LICENCIATURA EN CONTADURIA PUBLICA', 'title' => 'LICENCIADO EN CONTADURIA PUBLICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6353', 'new_code' => '258', 'name' => 'LICENCIATURA EN GERENCIA DE RECURSOS HUMANOS', 'title' => 'LICENCIADO EN GERENCIA DE RECURSOS HUMANOS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6355', 'new_code' => '259', 'name' => 'LICENCIATURA EN ADMINISTRACION COMERCIAL', 'title' => 'LICENCIADO EN ADMINISTRACION COMERCIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6357', 'new_code' => '260', 'name' => 'LICENCIATURA EN ADMINISTRACION INDUSTRIAL', 'title' => 'LICENCIADO EN ADMINISTRACION INDUSTRIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6360', 'new_code' => '261', 'name' => 'LICENCIATURA EN TURISMO', 'title' => 'LICENCIADO EN TURISMO', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6362', 'new_code' => '262', 'name' => 'LICENCIATURA EN HOTELERIA', 'title' => 'LICENCIADO EN HOTELERIA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6375', 'new_code' => '263', 'name' => 'LICENCIATURA EN TRABAJO SOCIAL', 'title' => 'LICENCIADO EN TRABAJO SOCIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6400', 'new_code' => '264', 'name' => 'LICENCIATURA EN SOCIOLOGIA', 'title' => 'LICENCIADO EN SOCIOLOGIA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6795', 'new_code' => '265', 'name' => 'TECNOLOGIA EN ESTADISTICA', 'title' => 'TECNOLOGO EN ESTADISTICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6815', 'new_code' => '266', 'name' => 'TECNOLOGIA EN ADMINISTRACION INDUSTRIAL', 'title' => 'TECNOLOGO EN ADMINISTRACION INDUSTRIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6864', 'new_code' => '267', 'name' => 'TECNOLOGIA PREVENCION DE RIESGO INDUSTRIAL', 'title' => 'TECNOLOGO EN PREVENCION DE RIESGO INDUSTRIAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6910', 'new_code' => '268', 'name' => 'TECNICO SUPERIOR EN ADMINISTRACION DE EMPRESAS TURISTICAS', 'title' => 'TECNICO SUPERIOR EN ADMINISTRACION DE EMPRESAS TURISTICAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6925', 'new_code' => '269', 'name' => 'TECNICO SUPERIOR EN ADMINISTRACION DE EMPRESAS HOTELERAS', 'title' => 'TECNICO SUPERIOR EN ADMINISTRACION DE EMPRESAS HOTELERAS', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '7000', 'new_code' => '270', 'name' => 'TSU EN ACUACULTURA MARINA', 'title' => 'TÉCNICO SUPERIOR EN ACUACULTURA MARINA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '1015E', 'new_code' => '271', 'name' => 'LIC. BIOLOGIA EXPERIMENTAL', 'title' => 'LICENCIADO EN BIOLOGIA EXPERIMENTAL', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5245CN', 'new_code' => '272', 'name' => 'EDUCACION INTEGRAL, MENCION CIENCIAS NATURALES', 'title' => 'LICENCIADO EN EDUCACION INTEGRAL, MENCION CIENCIAS NATURALES', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5245CS', 'new_code' => '273', 'name' => 'EDUCACION INTEGRAL, MENCION CIENCIAS SOCIALES', 'title' => 'LICENCIADO EN EDUCACION INTEGRAL, MENCION CIENCIAS SOCIALES', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5245L', 'new_code' => '274', 'name' => 'EDUCACION INTEGRAL, MENCION LENGUA', 'title' => 'LICENCIADO EN EDUCACION INTEGRAL, MENCION LENGUA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '5245M', 'new_code' => '275', 'name' => 'EDUCACION INTEGRAL, MENCION MATEMATICA', 'title' => 'LICENCIADO EN EDUCACION INTEGRAL, MENCION MATEMATICA', 'type' => '1', 'health_type' => '1']);
        Speciality::create(['code' => '6355A', 'new_code' => '276', 'name' => 'LICENCIATURA EN ADMINISTRACION COMERCIAL', 'title' => 'LICENCIADO EN ADMINISTRACION COMERCIAL', 'type' => '1', 'health_type' => '1']);
    }
}
